///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace HelloWorldKTSample2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the HelloWorldKTSample2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("83a06085-3921-406c-bbbb-c68185b00f6b")]
    public partial class HelloWorldKTSample2Repository : RepoGenBaseFolder
    {
        static HelloWorldKTSample2Repository instance = new HelloWorldKTSample2Repository();
        HelloWorldKTSample2RepositoryFolders.GoogleAppFolder _google;

        /// <summary>
        /// Gets the singleton class instance representing the HelloWorldKTSample2Repository element repository.
        /// </summary>
        [RepositoryFolder("83a06085-3921-406c-bbbb-c68185b00f6b")]
        public static HelloWorldKTSample2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public HelloWorldKTSample2Repository() 
            : base("HelloWorldKTSample2Repository", "/", null, 0, false, "83a06085-3921-406c-bbbb-c68185b00f6b", ".\\RepositoryImages\\HelloWorldKTSample2Repository83a06085.rximgres")
        {
            _google = new HelloWorldKTSample2RepositoryFolders.GoogleAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("83a06085-3921-406c-bbbb-c68185b00f6b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Google folder.
        /// </summary>
        [RepositoryFolder("19e11506-6475-4e2f-8b72-3406c7019163")]
        public virtual HelloWorldKTSample2RepositoryFolders.GoogleAppFolder Google
        {
            get { return _google; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class HelloWorldKTSample2RepositoryFolders
    {
        /// <summary>
        /// The GoogleAppFolder folder.
        /// </summary>
        [RepositoryFolder("19e11506-6475-4e2f-8b72-3406c7019163")]
        public partial class GoogleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputtagqInfo;
            RepoItemInfo _resultstatsInfo;

            /// <summary>
            /// Creates a new Google  folder.
            /// </summary>
            public GoogleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Google", "/dom[@domain='www.google.com']", parentFolder, 30000, null, false, "19e11506-6475-4e2f-8b72-3406c7019163", "")
            {
                _inputtagqInfo = new RepoItemInfo(this, "InputTagQ", ".//input[@title='Search']", 30000, null, "65535af5-1e60-4511-95e7-accd1442b488");
                _resultstatsInfo = new RepoItemInfo(this, "ResultStats", ".//div[@id='resultStatsxyz']", 30000, null, "65b61fc8-5eea-45cd-b4f6-3258a8418c4a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("19e11506-6475-4e2f-8b72-3406c7019163")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("19e11506-6475-4e2f-8b72-3406c7019163")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputTagQ item.
            /// </summary>
            [RepositoryItem("65535af5-1e60-4511-95e7-accd1442b488")]
            public virtual Ranorex.InputTag InputTagQ
            {
                get
                {
                    return _inputtagqInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagQ item info.
            /// </summary>
            [RepositoryItemInfo("65535af5-1e60-4511-95e7-accd1442b488")]
            public virtual RepoItemInfo InputTagQInfo
            {
                get
                {
                    return _inputtagqInfo;
                }
            }

            /// <summary>
            /// The ResultStats item.
            /// </summary>
            [RepositoryItem("65b61fc8-5eea-45cd-b4f6-3258a8418c4a")]
            public virtual Ranorex.DivTag ResultStats
            {
                get
                {
                    return _resultstatsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ResultStats item info.
            /// </summary>
            [RepositoryItemInfo("65b61fc8-5eea-45cd-b4f6-3258a8418c4a")]
            public virtual RepoItemInfo ResultStatsInfo
            {
                get
                {
                    return _resultstatsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}