///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HelloWorldKTSample2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TestModule recording.
    /// </summary>
    [TestModule("6a6b4099-fe1e-4f8a-aa2e-47d1529f75aa", ModuleType.Recording, 1)]
    public partial class TestModule : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HelloWorldKTSample2Repository repository.
        /// </summary>
        public static HelloWorldKTSample2Repository repo = HelloWorldKTSample2Repository.Instance;

        static TestModule instance = new TestModule();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TestModule()
        {
            Test = "2144";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TestModule Instance
        {
            get { return instance; }
        }

#region Variables

        string _Test;

        /// <summary>
        /// Gets or sets the value of variable Test.
        /// </summary>
        [TestVariable("09153c71-55a8-46e0-913c-cab53d419f8b")]
        public string Test
        {
            get { return _Test; }
            set { _Test = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Test' on item 'Google.InputTagQ'.", repo.Google.InputTagQInfo, new RecordItemIndex(0));
            repo.Google.InputTagQ.Element.SetAttributeValue("TagValue", Test);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
