///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HelloWorldKTSample2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TestModule2 recording.
    /// </summary>
    [TestModule("bcfcc308-d786-420b-91b2-504820f81f82", ModuleType.Recording, 1)]
    public partial class TestModule2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HelloWorldKTSample2Repository repository.
        /// </summary>
        public static HelloWorldKTSample2Repository repo = HelloWorldKTSample2Repository.Instance;

        static TestModule2 instance = new TestModule2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TestModule2()
        {
            testvar = "Test123";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TestModule2 Instance
        {
            get { return instance; }
        }

#region Variables

        string _testvar;

        /// <summary>
        /// Gets or sets the value of variable testvar.
        /// </summary>
        [TestVariable("711b30b1-3100-4546-be0b-0fa1742912fa")]
        public string testvar
        {
            get { return _testvar; }
            set { _testvar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
